- hosts: "{{ variable_host }}"
  tasks:
  - name: Hammer command to list all puppet proxy 
    command: hammer -u "{{ user }}" -p "{{ pass }}" proxy list
    register: command_output
    args:
      executable: /bin/bash
  - debug: msg="{{ command_output.stdout }}"
