- hosts: "{{ variable_host }}"
  tasks:
  - name: Hammer command to list all architectures
    command: hammer -u "{{ user }}" -p "{{ pass }}" architecture list
    register: command_output
    args:
      executable: /bin/bash
  - debug: msg="{{ command_output.stdout }}"
